# Generated by Django 4.2.6 on 2023-10-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urlshortner", "0002_url_long_url_url_time_created_alter_url_short_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="long_url",
            field=models.CharField(max_length=10000),
        ),
    ]
