# Generated by Django 4.2.6 on 2023-10-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urlshortner", "0003_alter_url_long_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="time_created",
        ),
        migrations.AlterField(
            model_name="url",
            name="short_url",
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
